config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :flights
  root to: 'users#new'
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	# create (post) action for when sign up form is submitted:
  post 'users' => 'users#create'
  	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :user
    has_many :passengers
    

    validates :Number, presence: true, length: { in: 3..7 }
    validates :originairport, presence: true, length: { in: 3..20 }

    validates_inclusion_of :passengersnumber, :in => 1..600, message: "Specify number of seats"
    validates_inclusion_of :seatsnumber, :in => 1..600, message: "specify number of passengers"

    

    validates_inclusion_of :price, :in => 1..9999, message: "Price must be between 1 and 9999"

    validate :arrivetime_is_after_departuretime
        validate :seatsnumber_is_greater_orequal_to_passengersnumber
    validate :originairport_is_different_from_destinationairport

    
    private
    def arrivetime_is_after_departuretime
        if departuretime >= arrivaltime
            errors.add(:arrivaltime, "cannot be before the departure time")
        end 
    end 

    def seatsnumber_is_greater_orequal_to_passengersnumber
        if seatsnumber < passengersnumber  
            errors.add(:passengersnumber,"cannot exceed the number of seats")
        end 
    end
    
    def originairport_is_different_from_destinationairport
        if originairport == destinationairport
            errors.add(:originairport, "The two airports must be different")
        end 
    end
    

    
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    before_action :set_flight, only: [:show, :edit, :update, :destroy]
    before_action :authorize
    # GET /flights
    # GET /flights.json

    def index
      @user = current_user
      @flights = @user.flights.all
    end
  
    # GET /flights/1
    # GET /flights/1.json
    def show
    end
  
    # GET /flights/new
    def new
      @flight = Flight.new
    end
  
    # GET /flights/1/edit
    def edit
    end
  
    # POST /flights
    # POST /flights.json
    def create
      @user = current_user
      @flight = @user.flights.new(flight_params)
  
  
      respond_to do |format|
        if @flight.save
          format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
          format.json { render :show, status: :created, location: @flight }
        else
          format.html { render :new }
          format.json { render json: @flight.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /flights/1
    # PATCH/PUT /flights/1.json
    def update
      respond_to do |format|
        if @flight.update(flight_params)
          format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
          format.json { render :show, status: :ok, location: @flight }
        else
          format.html { render :edit }
          format.json { render json: @flight.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /flights/1
    # DELETE /flights/1.json
    def destroy
      @flight.destroy
      respond_to do |format|
        format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_flight
        @flight = Flight.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def flight_params
        params.require(:flight).permit(:Number, :originairport, :destinationairport, :departuretime, :arrivaltime, :seatsnumber, :passengersnumber, :price)
      end
  end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Number %>
    <%= form.text_field :Number,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :originairport %>
    <%= form.text_field :originairport,class: "form-control" %>
     <%= form.hidden_field :post_id %>

  </div>
 
  <div class="form-group">
    <%= form.label :destinationairport %>
    <%= form.text_field :destinationairport,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :departuretime %>
    <%= form.datetime_select :departuretime,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :arrivaltime %>
    <%= form.datetime_select :arrivaltime,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :seatsnumber %>
    <%= form.number_field :seatsnumber,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :passengersnumber %>
    <%= form.number_field :passengersnumber,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price,class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights of <%= current_user.name %></h1>

<table class="table table-hover ">
  <thead>
    <tr>
      <th>Flight Number</th>
      <th>Origin airport</th>
      <th>Destination airport</th>
      <th>Departure time</th>
      <th>Arrival time</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.Number %></td>
        <td><%= flight.originairport %></td>
        <td><%= flight.destinationairport %></td>
        <td><%= (flight.departuretime) %></td>
        <td><%= flight.arrivaltime %></td>
        <td><%= link_to 'Show', flight ,class:"btn btn-primary btn-sm"%></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) ,class:"btn btn-primary btn-sm"%></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Flight', new_flight_path, class:"btn btn-primary btn-lg active"%>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>
<%= link_to 'Back', flights_path, class:"btn btn-primary"%>

app/views/flights/show.html.erb
<table class="table table-dark">
<tbody>
<tr>
<td>&nbsp;Flight number:</td>
<td>&nbsp;<strong><%= @flight.Number %></strong></td>
</tr>
<tr>
<td>&nbsp;Origin airport:</td>
<td>&nbsp; <strong><%=@flight.originairport%> </strong></td>
</tr>
<tr>
<td>&nbsp;Destination airport:</td>
<td>&nbsp;<strong><%=@flight.destinationairport%></strong></td>
</tr>
<tr>
<td>&nbsp;Departure time:</td>
<td>&nbsp;<strong><%=@flight.departuretime%></strong></td>
</tr>
<tr>
<td>&nbsp;Arrival time:</td>
<td>&nbsp;<strong><%= @flight.passengersnumber %></strong></td>
</tr>
<tr>
<td>&nbsp;Number of seats:</td>
<td>&nbsp;<strong><%=@flight.seatsnumber%></td>
</tr>
<tr>
<td>&nbsp;Number of passanger:</td>
<td>&nbsp;<strong><%= @flight.passengersnumber %></strong></td>
</tr>
<tr>
<td>&nbsp;Price of the ticket:</td>
<td>&nbsp;<strong><%= @flight.price %></strong></td>
</td>
</tr>
</tbody>
</table>

<%= link_to 'Edit', edit_flight_path(@flight),class:"btn btn-primary btn-lg active" %> 
<%= link_to 'Back', flights_path, class:"btn btn-primary btn-lg active"%>
<%= link_to 'Add new Passenger', new_passenger_path(flight_id: @flight.id), class: "btn btn-primary btn-lg active" %>