config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :flights
  root to: 'users#new'
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	# create (post) action for when sign up form is submitted:
  post 'users' => 'users#create'
  	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :flights
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]
  before_action :authorize  
  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end
  
  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new

    @passenger = Passenger.new()

  end

  # GET /passengers/1/edit
  def edit
  end

  def create
    @passenger = Passenger.new(passenger_params)
    respond_to do |format|
      if @passenger.save
        #p = Passenger.where(:id => :set_passenger.flight_id).first
        #p.increment(:seatsnumber)

        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:name, :passportnumber,:flight_id)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= form_with(model: passenger, local: true) do |form| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :passportnumber %>
    <%= form.text_field :passportnumber, class: "form-control" %>
          <%= form.hidden_field :flight_id %>

  </div>


  <div class="actions">
    <%= form.submit "Add Passenger",  class:"btn btn-primary"%>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Passportnumber</th>
      <th>Flight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.passportnumber %></td>
        <td><%= passenger.flight_id %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Passportnumber:</strong>
  <%= @passenger.passportnumber %>
</p>

<p>
  <strong>ID:</strong>
  <%= @passenger.flight_id %>
</p>

<%= link_to 'Back to Flight', flights_path(@passenger.flight_id) %>