config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :flights
  root to: 'users#new'
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	# create (post) action for when sign up form is submitted:
  post 'users' => 'users#create'
  	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      Done by Mustapha Kammoun 
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Flights Platform", flights_path , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to "Logged in as <b>#{current_user.name}</b>".html_safe, '#' %></li>

            <li><%= link_to 'Flights', flights_path %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
                
        <% else %>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
            <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFlight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>



    <div class="container">
    <% if notice %>
      <%= notice %>
    <% end %>
	
    <% if alert %>
      <%= alert %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>

  </body>
</html>